FROM node:20-alpine AS builder

WORKDIR /app
COPY backend/ .
RUN npm ci --legacy-peer-deps
RUN npm run build user-service

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist/apps/user-service ./dist
COPY --from=builder /app/package.json ./

CMD ["node", "dist/main"]
