FROM node:20-alpine AS builder

WORKDIR /app
COPY backend/package*.json ./
RUN npm ci --legacy-peer-deps

COPY backend/ .
RUN npm run build user-service

FROM node:20-alpine

WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist/apps/user-service ./dist
COPY backend/package*.json ./

CMD ["node", "dist/main"]
